BancoDigital/Banco/Banco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BancoDigital/Banco/app/urls.py
from django import views
from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language

urlpatterns = [
    path('', views.home, name='home'),
    path('registro/', views.registro, name='registro'),
    path('cadastrar-endereco/', views.cadastrar_endereco, name='cadastrar_endereco'),
    path('excluir_endereco/<int:endereco_id>/', views.excluir_endereco, name='excluir_endereco'),
    path('selecionar_agencia/', views.selecionar_agencia, name='selecionar_agencia'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('conta/', views.conta_view, name='conta'),
    path('perfil/', views.perfil, name='perfil'),
    path('solicitar_cartao/', views.solicitar_cartao, name='solicitar_cartao'),
    path('transacao/', views.realizar_transacao_view, name='transacao'),
    path('i18n/setlang/', set_language, name='set_language'),
    
]

BancoDigital/Banco/app/models.py
import uuid
import requests
from django.db.models import Sum
from django.db import models
from stdimage.models import StdImageField
from django.utils.translation import gettext_lazy as _
import random
from datetime import date, timedelta

from django.contrib.auth.models import AbstractUser, BaseUserManager

def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename

# Models


class Endereco(models.Model):
    ESTADO_CHOICES = [
        ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'),
        ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'),
        ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'),
        ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'),
        ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'),
        ('SE', 'SE'), ('TO', 'TO'),
    ]
    
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE, related_name='enderecos', null=True, blank=True)
    cep = models.CharField(_('CEP'), max_length=8)
    rua = models.CharField(_('Rua'), max_length=100)
    bairro = models.CharField(_('Bairro'), max_length=50)
    cidade = models.CharField(_('Cidade'), max_length=50)
    estado = models.CharField(_('Estado'), max_length=2, choices=ESTADO_CHOICES)
    numero = models.CharField(_('Número'), max_length=10)
    complemento = models.CharField(_('Complemento'), max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = _('Endereço')
        verbose_name_plural = _('Endereços')

    def __str__(self):
        return f'{self.bairro} - {self.rua} - {self.numero}'
    
    
    ###################################################################################



class ClienteManager(BaseUserManager):
    def create_user(self, CPF, email, password=None, **extra_fields):
        if not CPF:
            raise ValueError(_("O campo CPF é obrigatório."))
        if not email:
            raise ValueError(_("O campo email é obrigatório."))

        email = self.normalize_email(email)
        user = self.model(CPF=CPF, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, CPF, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superusuários precisam ter is_staff=True."))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Superusuários precisam ter is_superuser=True."))
        return self.create_user(CPF, email, password, **extra_fields)
    
    

class Cliente(AbstractUser):
    CPF = models.CharField(_('CPF'), max_length=11, unique=True, primary_key=True)
    telefone = models.CharField(_('Telefone'), max_length=11, null=False, blank=False, default='')
    foto = StdImageField(_('Foto'), null=True, blank=True, upload_to='clientes/',
                         variations={'thumb': {'width': 480, 'height': 480, 'crop': True}})

    first_name = models.CharField(_('Nome'), max_length=150, blank=False, null=False)
    last_name = models.CharField(_('Sobrenome'), max_length=150, blank=False, null=False)
    email = models.EmailField(_('E-Mail'), unique=True, blank=False, null=False)

    USERNAME_FIELD = "CPF"
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    objects = ClienteManager()  # Associa o manager personalizado

    class Meta:
        verbose_name = _('Cliente')
        verbose_name_plural = _('Clientes')

    def __str__(self):
        return self.CPF  # Retorna o CPF como string representativa

    def listar_enderecos(self):
        return ", ".join(str(endereco) for endereco in self.enderecos.all())
    listar_enderecos.short_description = 'Endereços'

    
###################################################################################


class Agencia(models.Model):
    nomeagencia = models.CharField(_('Nome da Agência'), max_length=100)
    numeroagencia = models.AutoField(_('Numero da Agencia'), primary_key=True, unique=True, editable=False)
    endereco = models.ForeignKey(Endereco, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Agência')
        verbose_name_plural = _('Agências')

    def __str__(self):
        return self.nomeagencia


###################################################################################

class Conta(models.Model):
    numeroConta = models.AutoField(_('Número da Conta'), primary_key=True, unique=True, editable=False)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    agencia = models.ForeignKey(Agencia, on_delete=models.CASCADE)
    dataAbertura = models.DateField(_('Data de Abertura'), auto_now_add=True)

    class Meta:
        verbose_name = _('Transação')
        verbose_name_plural = _('Transações')

    def __str__(self):
        return f'Transação {self.numeroTransacao}: {self.tipoTransacao} de {self.valor}'

    @property
    def saldo(self):
        total_creditos = self.transacoes.filter(
            tipoTransacao__in=['deposito'],
            status='concluida',
            contaDestino=self
        ).aggregate(Sum('valor'))['valor__sum'] or 0

        total_debitos = self.transacoes.filter(
            tipoTransacao__in=['saque'],
            status='concluida',
            conta=self
        ).aggregate(Sum('valor'))['valor__sum'] or 0

        return total_creditos - total_debitos

    def depositar(self, valor):
        if valor <= 0:
            raise ValueError("O valor do depósito deve ser positivo.")

    def sacar(self, valor):
        if valor <= 0:
            raise ValueError("O valor do saque deve ser positivo.")
        if self.saldo < valor:
            raise ValueError("Saldo insuficiente para realizar o saque.")

    def transferir(self, contaDestino, valor):
        if valor <= 0:
            raise ValueError("O valor da transferência deve ser positivo.")
        if self.saldo < valor:
            raise ValueError("Saldo insuficiente para realizar a transferência.")
        self.sacar(valor)
        contaDestino.depositar(valor)

    class Meta:
        verbose_name = _('Conta')
        verbose_name_plural = _('Contas')

    def __str__(self):
        return f'{self.cliente.first_name} {self.cliente.last_name} - {self.saldo}'


###################################################################################


class Transacao(models.Model):
    numeroTransacao = models.AutoField(_('Número da Transação'), primary_key=True)
    conta = models.ForeignKey(Conta, on_delete=models.CASCADE, related_name='transacoes')
    contaDestino = models.ForeignKey(Conta, on_delete=models.CASCADE, related_name='transacoes_destino', null=True, blank=False)
    valor = models.DecimalField(_('Valor'), max_digits=10, decimal_places=2)
    tipoTransacao = models.CharField(_('Tipo de Transação'), max_length=50, choices=[
        ('deposito', 'Depósito'),
        ('saque', 'Saque'),
        ('transferencia', 'Transferência')
    ], null=False, blank=False)
    status = models.CharField(_('Status'), max_length=20, default='pendente', editable=False)
    dataHora = models.DateTimeField(_('Data e Hora da Transação'), auto_now_add=True, null=True)

    def save(self, *args, **kwargs):
        if self.tipoTransacao == 'saque':
            self.conta.sacar(self.valor)
            self.status = 'concluida'
            super().save(*args, **kwargs)
            Notificacao.objects.create(
                conta=self.conta,
                mensagem=f"Saque no valor de R$ {self.valor:.2f} realizado com sucesso."
            )
            
        else:
            if self.tipoTransacao == 'deposito':
                self.conta.depositar(self.valor)
                self.status = 'concluida'
                super().save(*args, **kwargs)
                
                Notificacao.objects.create(
                    conta=self.conta,
                    mensagem=f"Depósito no valor de R$ {self.valor:.2f} realizado com sucesso."
                )
                
            else:
                if self.tipoTransacao == 'transferencia' and self.contaDestino:
                    saque = Transacao(
                        conta=self.conta,
                        contaDestino=self.conta,
                        valor=self.valor,
                        tipoTransacao='saque',
                        status='concluida',
                        dataHora=self.dataHora,)
                    saque.save()

                    deposito = Transacao(
                        conta=self.contaDestino,
                        contaDestino=self.contaDestino,
                        valor=self.valor,
                        tipoTransacao='deposito',
                        status='concluida',
                        dataHora=self.dataHora,)
                    deposito.save()
                    
                    Notificacao.objects.create(
                            conta=self.conta,
                            mensagem=(
                                f"Transferência no valor de R$ {self.valor:.2f} realizada com sucesso de "
                                f"{self.conta.cliente.get_full_name()} (Conta: {self.conta.numeroConta}) para "
                                f"{self.contaDestino.cliente.get_full_name()} (Conta: {self.contaDestino.numeroConta})."
                            )
                        )
                    
                    self.status = 'concluida'

            super().save(*args, **kwargs)
            # Cria uma única notificação com informações da transferência
  


    class Meta:
        verbose_name = _('Transação')
        verbose_name_plural = _('Transações')

    def __str__(self):
        return f'Transação {self.numeroTransacao}: {self.tipoTransacao} de {self.valor}'

BancoDigital/Banco/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Cliente, Conta, Transacao
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from .models import Endereco
from django.utils.translation import gettext_lazy as _  # Importando a função de tradução


class ClienteUserCreationForm(UserCreationForm):
    class Meta:
        model = Cliente
        fields = ('username', 'CPF', 'first_name', 'last_name', 'email', 'telefone', 'foto')
        
    def clean_CPF(self):
        cpf = self.cleaned_data.get('CPF')
        if Cliente.objects.filter(CPF=cpf).exists():
            raise forms.ValidationError(_('CPF já cadastrado.'))  # Tradução
        return cpf


class ClienteLoginForm(forms.Form):
    CPF = forms.CharField(max_length=11, label=_('CPF'), widget=forms.TextInput(attrs={'placeholder': _('Digite seu CPF')}))  # Tradução
    password = forms.CharField(widget=forms.PasswordInput(), label=_('Senha'))  # Tradução

    def clean_CPF(self):
        cpf = self.cleaned_data.get('CPF')
        try:
            # Verificar se o CPF existe na base de dados
            cliente = Cliente.objects.get(CPF=cpf)
        except Cliente.DoesNotExist:
            raise forms.ValidationError(_('CPF não encontrado.'))  # Tradução
        return cpf

    def clean(self):
        cleaned_data = super().clean()
        cpf = cleaned_data.get("CPF")
        password = cleaned_data.get("password")

        if cpf and password:
            # Tentando autenticar com o CPF e senha
            user = authenticate(username=cpf, password=password)
            if user is None:
                raise forms.ValidationError(_('Credenciais inválidas. Tente novamente.'))  # Tradução
        return cleaned_data


class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ['cep', 'rua', 'bairro', 'cidade', 'estado', 'numero', 'complemento']

        widgets = {
            'cep': forms.TextInput(attrs={'placeholder': _('Digite o CEP')}),  # Tradução
            'rua': forms.TextInput(attrs={'placeholder': _('Digite a rua')}),  # Tradução
            'bairro': forms.TextInput(attrs={'placeholder': _('Digite o bairro')}),  # Tradução
            'cidade': forms.TextInput(attrs={'placeholder': _('Digite a cidade')}),  # Tradução
            'estado': forms.Select(attrs={'placeholder': _('Escolha o estado')}),  # Tradução
            'numero': forms.TextInput(attrs={'placeholder': _('Digite o número')}),  # Tradução
            'complemento': forms.TextInput(attrs={'placeholder': _('Complemento (opcional)')}),  # Tradução
        }


class TransacaoForm(forms.ModelForm):
    class Meta:
        model = Transacao
        fields = ['conta', 'contaDestino', 'tipoTransacao', 'valor']

    def __init__(self, *args, **kwargs):
        cliente = kwargs.pop('cliente', None)  # Cliente logado
        tipo_transacao = kwargs.pop('tipo_transacao', None)  # Tipo de transação (Depósito, Saque ou Transferência)
        super().__init__(*args, **kwargs)

        # Filtra as contas do cliente para a conta de origem
        if cliente:
            self.fields['conta'].queryset = Conta.objects.filter(cliente=cliente)
        
        # Se for "Depósito" ou "Saque", mostra apenas a conta de origem para contaDestino
        if tipo_transacao in ['deposito', 'saque']:
            self.fields['contaDestino'].queryset = Conta.objects.filter(cliente=cliente)
        else:
            # Para "Transferência", permite escolher qualquer conta
            self.fields['contaDestino'].queryset = Conta.objects.all()

    def clean(self):
        cleaned_data = super().clean()
        tipo_transacao = cleaned_data.get('tipoTransacao')
        conta_origem = cleaned_data.get('conta')
        conta_destino = cleaned_data.get('contaDestino')

        # Verifica se a contaDestino é diferente da contaOrigem em Depósito ou Saque
        if tipo_transacao in ['deposito', 'saque'] and conta_origem != conta_destino:
            self.add_error('contaDestino', _('A conta de destino deve ser a mesma que a conta de origem para Depósito ou Saque.'))  # Tradução

        # Verifica se contaDestino está presente para transferência
        if tipo_transacao == 'transferencia' and not conta_destino:
            self.add_error('contaDestino', _('A conta de destino é obrigatória para transferências.'))  # Tradução

        return cleaned_data

BancoDigital/Banco/app/templates/cadastrar_endereco.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load i18n %}
    <title>{% trans "Cadastro de Endereço" %}</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static './static/style.css' %}">
</head>
<body>
    <header id="topo">
        <nav class="cabecalho">
            <ul class="cabecalho__menu">
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'home' %}">Home</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'conta' %}">{% trans "Conta" %}</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'perfil' %}">{% trans "Perfil" %}</a></li>
            </ul>
            <span class="app-name">Bank<span class="highlight">O!</span></span>
        </nav>
    </header>

    <div class="main-container">
        <h1>{% trans "Cadastro de Endereço" %}</h1>
        <form method="POST" class="form-endereco">
            {% csrf_token %}
            <div class="form-group">
                <label for="rua">{% trans "Rua" %}</label>
                {{ form.rua }}
            </div>
            <div class="form-group">
                <label for="numero">{% trans "Número" %}</label>
                {{ form.numero }}
            </div>
            <div class="form-group">
                <label for="bairro">{% trans "Bairro" %}</label>
                {{ form.bairro }}
            </div>
            <div class="form-group">
                <label for="cidade">{% trans "Cidade" %}</label>
                {{ form.cidade }}
            </div>

            <div class="form-group">
                <label for="estado">{% trans "Estado" %}</label>
                <select name="estado" id="id_estado" class="input-select">
                    {% for estado in form.estado.field.choices %}
                        <option value="{{ estado.0 }}" {% if estado.0 == form.estado.value %}selected{% endif %}>
                            {{ estado.1 }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="cep">{% trans "CEP" %}</label>
                {{ form.cep }}
            </div>

            <button type="submit" class="button">{% trans "Salvar Endereço" %}</button>
        </form>

        <br>
        <a href="{% url 'perfil' %}" class="button">{% trans "Voltar ao Perfil" %}</a>
    </div>

    <!-- Comutador de Idiomas -->
    <div class="language-switcher">
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% for lang_code, lang_name in LANGUAGES %}
                    <option value="{{ lang_code }}" {% if lang_code == LANGUAGE_CODE %}selected{% endif %}>
                        {{ lang_name }}
                    </option>
                {% endfor %}
            </select>
            <button type="submit">{% trans "Mudar Idioma" %}</button>
        </form>
    </div>

    <!-- Rodapé -->
    <footer class="rodape">
        <span class="app-name">Bank<span class="highlight">O!</span></span>
        <p class="rodape_texto">Desenvolvido por Cozta1.</p>
    </footer>
</body>
</html>

BancoDigital/Banco/app/templates/conta.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load i18n %} <!-- Carrega o módulo de internacionalização -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "Conta" %}</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static './static/style.css' %}"> <!-- Link para o arquivo de estilo CSS -->
    
    <script>
        function toggleNotifications() {
            const notificationsSection = document.getElementById('noti-section');
            notificationsSection.style.display = notificationsSection.style.display === 'none' || notificationsSection.style.display === '' ? 'block' : 'none';
        }
    </script>

</head>

<body>
    <header id="topo">
        <nav class="cabecalho">
            <ul class="cabecalho__menu">
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'home' %}">Home</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link__ativo" href="{% url 'conta' %}">{% trans "Conta" %}</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'perfil' %}">{% trans "Perfil" %}</a></li>
            </ul>
            <span class="app-name">Bank<span class="highlight">O!</span></span>
        </nav>
    </header>

    <!-- Conteúdo principal -->
    <div class="main-container">
        <h1 class="text-center">{% trans "Conta" %}</h1>

        <!-- Bloco de Informações do Usuário -->
        <div class="profile-info text-center">
            <div class="photo-container">
                {% if user.foto %}
                    <a href="{% url 'perfil' %}"><img src="{{ user.foto.url }}" alt="{% trans 'Foto do Usuário' %}" class="user-photo"></a>
                {% else %}
                    <div class="placeholder">A</div> <!-- Placeholder com a inicial do nome -->
                {% endif %}
            </div>
            <div class="name-container">
                <p>{{ user.first_name }} {{ user.last_name }}</p>
            </div>
        </div>

        <!-- Botão de Notificações centralizado -->
        <div class="button-container">
            <button class="button" onclick="toggleNotifications()">{% trans "Ultimas Transações" %}</button>
        </div>

        <!-- Seção de Notificações -->
        <div id="noti-section" class="cards-section">
            {% if notificacoes %}
                <ul>
                    {% for notificacao in notificacoes %}
                        <li>{{ notificacao.mensagem }} - {{ notificacao.dataHora|date:"d/m/Y H:i" }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "Não há notificações." %}</p>
            {% endif %}
        </div>

        <!-- Botões Centralizados -->
        <div class="button-container text-center">
            <a href="{% url 'transacao' %}" class="button">{% trans "Realizar Transação" %}</a>
            <button class="button" onclick="toggleCards()">{% trans "Meus Cartões" %}</button>
        </div>

        <!-- Seção de Cartões -->
        <div id="cards-section" class="cards-section text-center">
            <h3>{% trans "Cartões" %}</h3>
            {% if cartoes %}
                <ul>
                    {% for cartao in cartoes %}
                        <li>{{ cartao.bandeira }} - {{ cartao.numeroCartao }} - {% trans "Validade" %}: {{ cartao.dataExpiracao }} - CVV: {{ cartao.cvv }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "Você ainda não tem nenhum cartão." %}</p>
            {% endif %}
            <a href="{% url 'solicitar_cartao' %}" class="button">{% trans "Solicitar Novo Cartão" %}</a>
        </div>
        
        <!-- Comutador de Idiomas -->
        <div class="language-switcher text-center">
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% for lang_code, lang_name in LANGUAGES %}
                        <option value="{{ lang_code }}" {% if lang_code == LANGUAGE_CODE %}selected{% endif %}>
                            {{ lang_name }}
                        </option>
                    {% endfor %}
                </select>
                <button type="submit">{% trans "Mudar Idioma" %}</button>
            </form>
        </div>
    </div> <!-- Fim do main-container -->

    <!-- Rodapé -->
    <footer class="rodape text-center">
        <span class="app-name">Bank<span class="highlight">O!</span></span>
        <p class="rodape_texto">Desenvolvido por Cozta1.</p>
    </footer>

    <script>
        function toggleCards() {
            const cardsSection = document.getElementById('cards-section');
            cardsSection.style.display = cardsSection.style.display === 'none' || cardsSection.style.display === '' ? 'block' : 'none';
        }
    </script>
</body>
</html>

BancoDigital/Banco/app/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load i18n %} <!-- Carregar o módulo de internacionalização -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "Página Inicial" %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static './static/style.css' %}"> <!-- Link para o arquivo de estilo CSS -->

</head>
<body>
    <header id="topo">
        <nav class="cabecalho">
            <ul class="cabecalho__menu">
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link__ativo" href="{% url 'home' %}">Home</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'conta' %}">{% trans "Conta" %}</a></li>
                <li class="cabecalho__menu__item"><a class="cabecalho__menu__link" href="{% url 'perfil' %}">{% trans "Perfil" %}</a></li>
            </ul>
            <span class="app-name">Bank<span class="highlight">O!</span></span>
        </nav>
    </header>

    <div class="main-container">
        <h1 class="text-center">{% trans "Página Inicial" %}</h1>
            
            {% if user.is_authenticated %}
                <!-- Bloco de Informações do Usuário -->
                <div class="profile-info text-center">
                    <div class="photo-container">
                        {% if user.foto %}
                            <a href="{% url 'perfil' %}"><img src="{{ user.foto.url }}" alt="{% trans 'Foto do Usuário' %}" class="user-photo"></a>
                        {% else %}
                            <div class="placeholder">A</div> <!-- Placeholder com a inicial do nome -->
                        {% endif %}
                    </div>
                    <div class="name-container">
                        <p>{{ user.first_name }} {{ user.last_name }}</p>
                    </div>
                </div>

                <div class="button-container">
                    <a href="{% url 'perfil' %}" class="button">{% trans "Meu Perfil" %}</a>
                    <a href="{% url 'conta' %}" class="button">{% trans "Minha Conta" %}</a>
                    <a href="{% url 'logout' %}" class="button">{% trans "Sair" %}</a>
                </div>

            {% else %}
                <p>{% trans "Bem-vindo ao nosso site! Por favor," %} <a href="{% url 'login' %}">{% trans "faça login" %}</a> {% trans "para acessar sua conta." %}</p>
                <a href="{% url 'registro' %}" class="button">{% trans "Cadastre-se" %}</a>
            {% endif %}
            
            <!-- Comutador de Idiomas -->
            <div class="language-switcher">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <select name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% for lang_code, lang_name in LANGUAGES %}
                            <option value="{{ lang_code }}" {% if lang_code == LANGUAGE_CODE %}selected{% endif %}>
                                {{ lang_name }}
                            </option>
                        {% endfor %}
                    </select>
                    <button type="submit">{% trans "Mudar Idioma" %}</button>
                </form>
            </div>
        </div>

    <!-- Rodapé -->
    <footer class="rodape text-center">
        <span class="app-name">Bank<span class="highlight">O!</span></span>
        <p class="rodape_texto">Desenvolvido por Cozta1.</p>
    </footer>
    </div>
</body>
</html>

BancoDigital/Banco/app/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load i18n %} <!-- Carregar o módulo de internacionalização -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "Login" %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static './static/style.css' %}">
</head>
<body>

    <div class="main-container">
        <h1>{% trans "Login" %}</h1>

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_CPF">{% trans "CPF" %}</label>
                {{ form.CPF }}
            </div>
            <div class="form-group">
                <label for="id_password">{% trans "Senha" %}</label>
                {{ form.password }}
            </div>
            <button type="submit" class="button">{% trans "Entrar" %}</button>

            {% if form.non_field_errors %}
                <div class="error">
                    <ul>
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </form>

        <div class="login-link">
            <p>{% trans "Ainda não tem uma conta?" %} <a href="{% url 'registro' %}" class="back-btn">{% trans "Cadastre-se!" %}</a></p>
        </div>
        {% comment %} <a href="{% url 'registro' %}" class="back-btn">{% trans "Ainda não tem uma conta? Cadastre-se!" %}</a> {% endcomment %}

        <!-- Comutador de Idiomas -->
        <div class="language-switcher">
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% for lang_code, lang_name in LANGUAGES %}
                        <option value="{{ lang_code }}" {% if lang_code == LANGUAGE_CODE %}selected{% endif %}>
                            {{ lang_name }}
                        </option>
                    {% endfor %}
                </select>
                <button type="submit">{% trans "Mudar Idioma" %}</button>
            </form>
        </div>
    </div>

    <!-- Rodapé -->
    <footer class="rodape">
        <span class="app-name">Bank<span class="highlight">O!</span></span>
        <p class="rodape_texto">Desenvolvido por Cozta1.</p>
    </footer>
</body>
</html>